apiVersion: v1
data:
  CreateDB.sql: |-
    CREATE TABLE blog_post (
            id SERIAL PRIMARY KEY, 
            title VARCHAR (250) NOT NULL, date VARCHAR (250) NOT NULL, 
            body TEXT NOT NULL, author VARCHAR (250) NOT NULL, 
            img_url VARCHAR (250) NOT NULL, subtitle VARCHAR (250) NOT NULL, 
            UNIQUE (title)
            );
kind: ConfigMap
metadata:
  name: pg-init-script
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: sqlscript
          mountPath: /docker-entrypoint-initdb.d
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
      volumes:
        - name: sqlscript
          configMap:
            name: pg-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 5432